"""
Generated by Claude due to laziness. 

DeepRole
The Resistance: Avalon, 5-player variant with Merlin + Assassin. 
 
Roles in 5-player Avalon:
  - Merlin                         (Arthur side, knows all spies)
  - Loyal Servant x2               (no special info)
  - Assassin                       (Mordred side, can target Merlin at end)
  - Disloyal Servant               (Mordred side)
 
Public game flow (Fig. 1 of the paper):
  Round r in 0..4:
    Up to 5 proposals:
      1. Proposer (rotating) picks a team of TEAM_SIZES[r] players.
      2. All 5 players simultaneously vote yes/no.
      3. If majority approve -> mission.
         Else -> next proposer; on the 5th rejection total, Mordred win.
    Mission: each team member privately chooses succeed/fail.
      Arthur's knights must choose succeed; Mordred's minions may choose either.
      Mission fails if any chose fail. Public outcome = (#fails).
  3 successes -> Arthur reaches assassination phase.
    Assassin picks a player; if it's Merlin, Mordred win, else Arthur wins.
  3 failures -> Mordred win immediately.
 
Design notes
------------
Simultaneous moves (votes, mission plays) are exposed as bulk-action methods
that take a full vector at once. This matches how vector-form CFR will want
to query and update the game.
 
State is split into:
  - 'assignment'    : the hidden role tuple (sampled at game start)
  - 'public'        : everything any observer can see (history of obs)
  - 'phase'         : whose turn / what kind of action is expected next
 
For belief tracking and CFR we never want to peek at 'assignment' from
non-omniscient code paths — the GameState class makes that separation
explicit by exposing observation() and information_set(player) helpers.

Thanks Claude.
"""
 
from __future__ import annotations
 
from dataclasses import dataclass, field
from enum import Enum
from itertools import permutations
from typing import List, Optional, Tuple
from random import random
 
 
# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
 
NUM_PLAYERS = 5
NUM_ROUNDS = 5
TEAM_SIZES = [2, 3, 2, 3, 3]          # team size for round 0..4
MAX_PROPOSALS = 5                     
WIN_MISSIONS = 3                      # no. of successes (or fails) needed to win

 
class Role(Enum):
    LS = "L"
    MERLIN = "M"
    DS = "D" 
    ASSASSIN = "A"
 
    def is_evil(self) -> bool:
        return self in (Role.DS, Role.ASSASSIN)
 
    def is_good(self) -> bool:
        return not self.is_evil()
 
 
# Multiset of roles present in 5-player Avalon: 1 Merlin, 2 LS (Loyal Servant),
# 1 Assassin, 1 DS (Disloyal Servant). There are 5! / (1! 2! 1! 1!) = 60 distinct assignments.
ROLE_MULTISET: Tuple[Role, ...] = (
    Role.MERLIN,
    Role.LS,
    Role.LS,
    Role.DS,
    Role.ASSASSIN,
)
 
 
def _enumerate_assignments() -> List[Tuple[Role, ...]]:
    seen = set()
    out: List[Tuple[Role, ...]] = []
    for perm in permutations(ROLE_MULTISET):
        if perm not in seen:
            seen.add(perm)
            out.append(perm)
    return out
 
 
ASSIGNMENTS: List[Tuple[Role, ...]] = _enumerate_assignments()
assert len(ASSIGNMENTS) == 60, "should have 60 assignments"
 
 
# ---------------------------------------------------------------------------
# Phases
# ---------------------------------------------------------------------------
 
class Phase(Enum):
    PROPOSE = "propose"          # proposer picks a team
    VOTE = "vote"                # all 5 vote yes/no
    MISSION = "mission"          # team members privately play succeed/fail
    ASSASSINATE = "assassinate"  # Assassin guesses Merlin
    TERMINAL = "terminal"        # Game over
 
 
# ---------------------------------------------------------------------------
# Game state
# ---------------------------------------------------------------------------
 
@dataclass
class Proposal:
    proposer: int
    team: Tuple[int, ...]
    votes: Optional[Tuple[bool, ...]] = None     # one bool per player
    approved: Optional[bool] = None
 
 
@dataclass
class RoundRecord:
    proposals: List[Proposal] = field(default_factory=list)
    mission_fails: Optional[int] = None          # # of fail plays; None if not yet played
    succeeded: Optional[bool] = None
 
 
@dataclass
class GameState:
    """Full game state. Stores the hidden assignment alongside public history.
    Always read public history via observation()/information_set() in code that
    must not see hidden roles."""
 
    assignment: Tuple[Role, ...]
    rounds: List[RoundRecord] = field(default_factory=lambda: [RoundRecord()])
    round_idx: int = 0                  # which round we're in (0..4)
    proposer: int = 0                   # current proposer
    phase: Phase = Phase.PROPOSE
    successes: int = 0
    failures: int = 0
    rejected_proposals: int = 0
    assassin_target: Optional[int] = None
    winner: Optional[str] = None        # "Arthur" | "Mordred"
 
    # ---- accessors -------------------------------------------------------
 
    def team_size(self) -> int:
        return TEAM_SIZES[self.round_idx]
 
    @property
    def current_round(self) -> RoundRecord:
        return self.rounds[self.round_idx]
 
    @property
    def current_proposal(self) -> Optional[Proposal]:
        if not self.current_round.proposals:
            return None
        return self.current_round.proposals[-1]
 
    def is_terminal(self) -> bool:
        return self.phase is Phase.TERMINAL
 
    # ---- transitions -----------------------------------------------------
 
    def propose(self, team: Tuple[int, ...]) -> None:
        assert self.phase is Phase.PROPOSE
        assert len(team) == self.team_size()
        assert len(set(team)) == len(team)
        assert all(0 <= p < NUM_PLAYERS for p in team)
        self.current_round.proposals.append(
            Proposal(proposer=self.proposer, team=tuple(sorted(team)))
        )
        self.phase = Phase.VOTE
 
    def vote(self, votes: Tuple[bool, ...]) -> None:
        assert self.phase is Phase.VOTE
        assert len(votes) == NUM_PLAYERS
        prop = self.current_proposal
        prop.votes = tuple(votes)
        approved = sum(votes) > NUM_PLAYERS // 2     # strict majority
        prop.approved = approved
 
        if approved:
            self.phase = Phase.MISSION
        else:
            self.rejected_proposals += 1
            if self.rejected_proposals >= MAX_PROPOSALS:    # game ends when there is 5 rejected proposals
                self.phase = Phase.TERMINAL
                self.winner = "mordred"
            else:
                self.proposer = (self.proposer + 1) % NUM_PLAYERS
                self.phase = Phase.PROPOSE
 
    def play_mission(self, plays: dict) -> None:
        """plays: {player_id: bool} for every team member.
        True = succeed, False = fail. Arthur side MUST play True; we enforce
        only the public observable (count of fails)."""
        assert self.phase is Phase.MISSION
        team = self.current_proposal.team
        assert set(plays.keys()) == set(team), "must have one play per team member"
        # Sanity check: Arthur/Merlin must have played succeed.
        for p in team:
            if self.assignment[p].is_good():
                assert plays[p] is True, (
                    f"good player {p} ({self.assignment[p]}) must succeed"
                )
        fails = sum(1 for p in team if plays[p] is False)
        rec = self.current_round
        rec.mission_fails = fails
        rec.succeeded = (fails == 0)
        if rec.succeeded:
            self.successes += 1
        else:
            self.failures += 1
 
        # Win/lose check.
        if self.failures >= WIN_MISSIONS:
            self.phase = Phase.TERMINAL
            self.winner = "mordred"
            return
        if self.successes >= WIN_MISSIONS:
            self.phase = Phase.ASSASSINATE
            return
 
        # Advance to next round.
        self.round_idx += 1
        self.rounds.append(RoundRecord())
        self.proposer = (self.proposer + 1) % NUM_PLAYERS
        self.phase = Phase.PROPOSE
 
    def assassinate(self, target: int) -> None:
        self.assassin = next(i for i, r in enumerate(self.assignment) if r is Role.ASSASSIN)
        assert self.phase is Phase.ASSASSINATE
        assert 0 <= target < NUM_PLAYERS
        assert target != self.assassin 

        self.assassin_target = target
        if self.assignment[target] is Role.MERLIN:
            self.winner = "mordred"
        else:
            self.winner = "arthur"
        self.phase = Phase.TERMINAL
 
    # ---- observation / information sets ----------------------------------
 
    def observation(self) -> dict:
        """Strictly-public view of the game. Used by any code that must not
        see hidden roles (belief tracker, CFR, value net inputs)."""
        return {
            "round_idx": self.round_idx,
            "proposer": self.proposer,
            "phase": self.phase.value,
            "successes": self.successes,
            "failures": self.failures,
            "rejected_proposals": self.rejected_proposals,
            "rounds": [
                {
                    "proposals": [
                        {
                            "proposer": pr.proposer,
                            "team": pr.team,
                            "votes": pr.votes,
                            "approved": pr.approved,
                        }
                        for pr in r.proposals
                    ],
                    "mission_fails": r.mission_fails,
                    "succeeded": r.succeeded,
                }
                for r in self.rounds
            ],
            "assassin_target": self.assassin_target,
            "winner": self.winner,
        }
 
    def information_set(self, player: int) -> dict:
        """What `player` knows: public history + their private role-induced info."""
        info = self.observation()
        my_role = self.assignment[player]
        info["self_role"] = my_role.value
        # Mordred team mutual knowledge:
        if my_role.is_evil():
            info["evil_team"] = tuple(
                i for i, r in enumerate(self.assignment) if r.is_evil()
            )
        # Merlin sees evil:
        if my_role is Role.MERLIN:
            info["evil_team"] = tuple(
                i for i, r in enumerate(self.assignment) if r.is_evil()
            )
        return info
 
    # ---- utilities -------------------------------------------------------
 
    def utility(self, player: int) -> int:
        """+1 win, -1 loss, 0 if not terminal."""
        if not self.is_terminal():
            return 0
        my_role = self.assignment[player]
        won = (
            (self.winner == "arthur" and my_role.is_good())
            or (self.winner == "mordred" and my_role.is_evil())
        )
        return 1 if won else -1
 
 
# ---------------------------------------------------------------------------
# Factory
# ---------------------------------------------------------------------------
 
def new_game(assignment: Optional[Tuple[Role, ...]] = None,
             rng=None,
             first_proposer: int = 0) -> GameState:
    """Create a new GameState. If assignment is None, sample uniformly from
    the 60 possible assignments."""
    if assignment is None:
        if rng is None: 
            import random
            rng = random.Random()
        assignment = rng.choice(ASSIGNMENTS)
    return GameState(assignment=tuple(assignment), proposer=first_proposer)
 
 
# ---------------------------------------------------------------------------
# Smoke test
# ---------------------------------------------------------------------------
 
if __name__ == "__main__":
    import random
    rng = random.Random(0)
    
    g = new_game(rng=rng)
    print("Hidden assignment:", [r.value for r in g.assignment])
    
    # ---------------------------------------------------------------------------
    # Round 0: Pre-game
    # ---------------------------------------------------------------------------
    obs = g.observation()
    print("\n--- Public observation snapshot R0 ---")
    print("round_idx:", obs["round_idx"])
    print("proposer:", obs["proposer"])
    print("successes:", obs["successes"])
    print("failures:", obs["failures"])
    print("phase:", obs["phase"])
    print("rejected_proposals:", obs["rejected_proposals"])
    print("winner:", obs["winner"])
    
    # ---------------------------------------------------------------------------
    # Round 1: Proposer picks two players
    # ---------------------------------------------------------------------------
    g.propose((0, 1))
    g.vote((True, True, True, False, False))   # 3-2 approved
    plays = {p: g.assignment[p].is_good() for p in g.current_proposal.team}
    g.play_mission(plays)
    print("After R1: successes=", g.successes, "failures=", g.failures)
    print("Phase:", g.phase)
    
    obs = g.observation()
    print("\n--- Public observation snapshot R1 ---")
    print("round_idx:", obs["round_idx"])
    print("proposer:", obs["proposer"])
    print("successes:", obs["successes"])
    print("failures:", obs["failures"])
    print("phase:", obs["phase"])
    print("rejected_proposals:", obs["rejected_proposals"])
    print("winner:", obs["winner"])
    
    # ---------------------------------------------------------------------------
    # Round 2: Proposer picks three players
    # ---------------------------------------------------------------------------
    g.propose((0, 1, 2))
    g.vote((True, True, False, False, False))   # 2-3 failed
    g.propose((0, 1, 2))
    g.vote((True, True, False, False, False))   # 2-3 failed
    g.propose((0, 1, 2))
    g.vote((True, True, False, False, False))   # 2-3 failed
    g.propose((0, 1, 2))
    g.vote((True, True, False, False, False))   # 2-3 failed
    g.propose((0, 1, 2))
    g.vote((True, True, False, False, False))   # 2-3 failed
    obs = g.observation()
    print("\n--- Public observation snapshot R2 ---")
    print("round_idx:", obs["round_idx"])
    print("proposer:", obs["proposer"])
    print("successes:", obs["successes"])
    print("failures:", obs["failures"])
    print("phase:", obs["phase"])
    print("rejected_proposals:", obs["rejected_proposals"])
    print("winner:", obs["winner"])

    # ---------------------------------------------------------------------------
    # Debug mode
    # ---------------------------------------------------------------------------
    # g = new_game(rng=rng)
    # while g.phase != Phase.TERMINAL and g.phase != Phase.ASSASSINATE:        
    #     team = tuple(range(g.team_size()))
    #     g.propose(team)
    #     g.vote((True, True, True, True, True))
    #     plays = {p: True for p in team}
    #     g.play_mission(plays)
    #     obs = g.observation()
    #     print(f"\n--- Public observation snapshot R{g.round_idx + 1} ---")
    #     print("round_idx:", obs["round_idx"])
    #     print("proposer:", obs["proposer"])
    #     print("successes:", obs["successes"])
    #     print("failures:", obs["failures"])
    #     print("phase:", obs["phase"])
    #     print("rejected_proposals:", obs["rejected_proposals"])
    #     print("winner:", obs["winner"])

    # print("FINAL WINNER:", g.winner)
    
    # print(list(enumerate(g.assignment)))
    # g.assassinate(2)
    # print(f"\n--- Public observation snapshot R{g.round_idx + 1} ---")
    # print("round_idx:", obs["round_idx"])
    # print("proposer:", obs["proposer"])
    # print("successes:", obs["successes"])
    # print("failures:", obs["failures"])
    # print("phase:", obs["phase"])
    # print("rejected_proposals:", obs["rejected_proposals"])
    # print("winner:", obs["winner"])

    # print("FINAL WINNER:", g.winner)