"""
Training pipeline.

Implements Algorithm 3 (ENDTOENDTRAIN / GENERATEDATAPOINTS) of Serrino et al.
(2019). Trains the 45-network ValueBank in dependency-graph order: each
(proposer, s, f) network is trained on data generated by SOLVESITUATION
(CFRSolver), which uses the value bank's already-trained downstream networks
at depth-limited leaves.

For laptop scale (Q4=a) we expose configurable knobs and ship laptop-friendly
defaults. The full paper scale (120K samples × 1500 iters per network) is
not the default but is reachable by setting the knobs.

Public API:
  generate_datapoints(s, f, value_bank, n_samples, n_cfr_iters, ...)
    → list of (proposer:int, belief:np.ndarray(60,), V_target:np.ndarray(60,))
  train_value_network(net, dataset, *, epochs, batch_size, lr, val_split)
    → dict with 'train_losses' and 'val_losses' lists per epoch
  endtoend_train(value_bank, *, n_samples_per_part, n_cfr_iters, epochs, ...)
    → trained ValueBank (in place; returns same instance for convenience)

Game-part dependency graph (paper Figure 1, left):
  (s, f) depends on (s+1, f) and (s, f+1) — i.e. on game-parts deeper in the
  game. We train deepest first (s=2, f=2), so by the time CFR reaches a
  ValueNetLeaf inside the subgame we're sampling for, that leaf's network is
  already trained.

Notes on V target:
  CFRSolver returns counterfactual values V[i, j] of shape (5, 15). The value
  network's output is per-assignment "P(good wins)" w[a] of shape (60,). To
  derive a target w from CFR's V, we invert the readout: the network's output
  must approximately reproduce w·M_i·b — the simplest target is the
  "probability-weighted value at the LS info set" averaged appropriately.
  See _v_target_from_cfr below.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import numpy as np
import torch
import torch.nn as nn
from torch.optim import Adam
from torch.utils.data import DataLoader, TensorDataset, random_split

from src.assignments import (
    INFO_SET_INDEX,
    INFO_SETS_PER_PLAYER,
    M_MATRIX,
    NUM_ASSIGNMENTS,
)
from src.cfr import CFRSolver, ProposeState
from src.game import NUM_PLAYERS, Role
from src.situation_sampler import sample_situation
from src.value_bank import ValueBank
from src.value_net import GOOD_MASK


# ---------------------------------------------------------------------------
# V target: distill CFR's per-info-set values into per-assignment w
# ---------------------------------------------------------------------------

def _v_target_from_cfr(
    cf_values_root: np.ndarray,
    belief: np.ndarray,
) -> np.ndarray:
    """Convert CFR root counterfactual values V[i, j] (shape (5, 15)) into a
    per-assignment "P(good wins)" target w[a] of shape (60,) for net training.

    Reasoning. The network outputs w[a] = P(good wins | ρ=a). The readout
    multiplies by M_i to give per-info-set values. We invert by the rule:
      w[a] = (V[i, INFO_SET_INDEX[i, a]] + 1) / 2 if i is good under ρ=a
           = (1 − (V[i, …] + 1) / 2)              if i is evil
    averaged across i to reduce variance, weighted by belief.

    Concretely, V[i, j] in our convention is in [-1, +1] (utilities). We map
    "probability good wins, as seen by player i in this assignment":
      For good i:  prob = (V + 1) / 2.
      For evil i:  prob = 1 - (V + 1) / 2 = (1 - V) / 2.

    Average across the 5 players (with belief-weighted normalization at the
    info-set level) to land on a single per-ρ target.
    """
    # Per (i, ρ): info-set j_i = INFO_SET_INDEX[i, ρ]; value V[i, j_i].
    # Convert V[i, j] → "prob good wins under ρ":
    #   if i is good in ρ: p = (V + 1) / 2
    #   if i is evil:      p = (1 - V) / 2
    n_players, n_assignments = NUM_PLAYERS, NUM_ASSIGNMENTS
    per_player = np.zeros((n_players, n_assignments), dtype=np.float64)
    for i in range(n_players):
        v_i = cf_values_root[i, INFO_SET_INDEX[i]]   # (60,)
        good = GOOD_MASK[i].astype(np.float64)
        prob = good * ((v_i + 1.0) / 2.0) + (1.0 - good) * ((1.0 - v_i) / 2.0)
        per_player[i] = prob
    target = per_player.mean(axis=0)
    return np.clip(target, 0.0, 1.0)


# ---------------------------------------------------------------------------
# generate_datapoints — Algorithm 3 GENERATEDATAPOINTS
# ---------------------------------------------------------------------------

@dataclass
class Datapoint:
    proposer: int
    belief: np.ndarray   # (60,)
    target: np.ndarray   # (60,)


def _root_for_part(proposer: int, s: int, f: int) -> ProposeState:
    """Construct the subgame root for (proposer, s, f) at the appropriate round.

    In 5p Avalon the round_idx is determined by the count of past missions
    (s + f). Rejected_count starts at 0 (a fresh proposal in this round).
    """
    return ProposeState(
        round_idx=s + f, proposer=proposer,
        successes=s, failures=f, rejected_count=0,
    )


def generate_datapoints(
    s: int,
    f: int,
    value_bank: ValueBank,
    n_samples: int,
    n_cfr_iters: int,
    averaging_delay: int = 0,
    rng: Optional[np.random.Generator] = None,
) -> List[Datapoint]:
    """Generate (proposer, belief, V_target) datapoints for game-part (s, f).

    For each sample: draw a (proposer, belief) via sample_situation(s, f),
    construct the subgame root, run CFR for n_cfr_iters, and read the root's
    counterfactual values.
    """
    assert 0 <= s < 3 and 0 <= f < 3, (s, f)
    if rng is None:
        rng = np.random.default_rng()

    out: List[Datapoint] = []
    for _ in range(n_samples):
        proposer, belief = sample_situation(s, f, rng=rng)
        root = _root_for_part(proposer, s, f)
        solver = CFRSolver(root, value_bank, prior_belief=belief)
        solver.solve(n_iters=n_cfr_iters, averaging_delay=averaging_delay)
        # Pull root counterfactual values: re-run forward pass once with the
        # converged average strategy. Simplest approximation: use the σ from
        # the last iteration (which is current regret-matching σ at root).
        # Cleaner: re-run _iteration once with w=0 to get counterfactual
        # values without polluting strategy_sum. For laptop scale the
        # cleanliness is overkill; the regret-matched σ at iteration N is
        # close enough.
        v_root = _root_counterfactual_values(solver)
        target = _v_target_from_cfr(v_root, belief)
        out.append(Datapoint(proposer=proposer, belief=belief, target=target))
    return out


def _root_counterfactual_values(solver: CFRSolver) -> np.ndarray:
    """Recompute counterfactual values at the root using the solver's current
    average-strategy table. Returns (5, 15)."""
    # Use the average strategy as the "current" strategy for one final pass.
    avg = solver.average_strategies()

    # Walk the DAG forward then backward (mirror of _iteration) but with σ
    # from average strategy (a stable converged-ish strategy). w=0 ensures
    # strategy_sum isn't perturbed.
    # We piggyback on _iteration's structure by temporarily replacing regrets
    # with values that re-derive the average σ. Simpler: read off the σ
    # directly and run forward + backward by hand.
    state_reach: Dict = {solver._root_key: np.ones((NUM_PLAYERS, 15), dtype=np.float64)}
    for state_key in solver._topo_order:
        state, mask = solver._states[state_key]
        if state_key not in state_reach:
            continue
        from src.cfr import is_leaf
        if is_leaf(state):
            continue
        reach = state_reach[state_key]
        for o, child_key in solver._edges[state_key]:
            child_reach = _propagate_reach_with_avg(
                solver, state, state_key, o, avg, reach
            )
            if child_key in state_reach:
                state_reach[child_key] = state_reach[child_key] + child_reach
            else:
                state_reach[child_key] = child_reach

    state_u: Dict = {}
    from src.cfr import (
        AssassinateOutcomeState, TerminalState, ValueNetLeafState,
        moving_players, num_actions,
    )
    for state_key in reversed(solver._topo_order):
        state, mask = solver._states[state_key]
        reach = state_reach.get(state_key)
        if reach is None:
            continue
        if isinstance(state, TerminalState):
            state_u[state_key] = solver._terminal_cfvs(state, solver.prior_belief, reach, mask)
            continue
        if isinstance(state, ValueNetLeafState):
            state_u[state_key] = solver._neural_cfvs(state, solver.prior_belief, reach, mask)
            continue
        if isinstance(state, AssassinateOutcomeState):
            state_u[state_key] = solver._assassinate_outcome_cfvs(state, solver.prior_belief, reach, mask)
            continue
        movers = moving_players(state)
        u = np.zeros((NUM_PLAYERS, 15), dtype=np.float64)
        for o, child_key in solver._edges[state_key]:
            u_child = state_u[child_key]
            actions_o, _ = solver._actions_with_factors(
                state, state_key, o, _avg_to_sigma_dict(solver, avg)
            )
            for i in range(NUM_PLAYERS):
                if i in movers:
                    sigma_i = avg.get((state_key, i))
                    if sigma_i is None:
                        sigma_i = np.ones((15, num_actions(state, i))) / num_actions(state, i)
                    factor = (sigma_i * actions_o[i]).sum(axis=-1)
                    u[i] += factor * u_child[i]
                else:
                    u[i] += u_child[i]
        state_u[state_key] = u

    return state_u[solver._root_key]


def _avg_to_sigma_dict(solver: CFRSolver, avg: Dict) -> Dict:
    """Adapt average_strategies output to the (state_key, player) σ dict format
    expected by solver._actions_with_factors."""
    return avg


def _propagate_reach_with_avg(solver, state, state_key, observation, sigma, reach):
    """Reach propagation using the supplied σ dict. Mirror of CFRSolver._propagate_reach."""
    actions_o, sentinel_reach = solver._actions_with_factors(state, state_key, observation, sigma)
    from src.cfr import moving_players, num_actions
    movers = moving_players(state)
    child_reach = reach.copy()
    for i in movers:
        sigma_i = sigma.get((state_key, i))
        if sigma_i is None:
            sigma_i = np.ones((15, num_actions(state, i))) / num_actions(state, i)
        factor = (sigma_i * actions_o[i]).sum(axis=-1)
        for (mover, j), rf in sentinel_reach.items():
            if mover == i:
                factor[j] = rf
        child_reach[i] = reach[i] * factor
    return child_reach


# ---------------------------------------------------------------------------
# train_value_network — Adam + MSE on per-assignment w
# ---------------------------------------------------------------------------

def train_value_network(
    net: nn.Module,
    dataset: List[Datapoint],
    *,
    epochs: int = 500,
    batch_size: int = 4096,
    lr: float = 1e-3,
    val_split: float = 0.1,
    device: str = "cpu",
    seed: int = 0,
) -> Dict[str, list]:
    """Train one ValueNetwork in place. Returns per-epoch train/val losses.

    Loss: MSE between net(proposer, belief) and target w. Both are (60,)
    float32 internally. Validation loss is the MSE on a held-out split.
    """
    if not dataset:
        return {"train_losses": [], "val_losses": []}

    proposers = torch.tensor([d.proposer for d in dataset], dtype=torch.long)
    beliefs = torch.tensor(np.stack([d.belief for d in dataset]), dtype=torch.float32)
    targets = torch.tensor(np.stack([d.target for d in dataset]), dtype=torch.float32)

    full = TensorDataset(proposers, beliefs, targets)
    n_val = max(1, int(len(full) * val_split)) if len(full) > 1 else 0
    n_train = len(full) - n_val
    gen = torch.Generator().manual_seed(seed)
    if n_val > 0:
        train_ds, val_ds = random_split(full, [n_train, n_val], generator=gen)
    else:
        train_ds, val_ds = full, None

    train_loader = DataLoader(
        train_ds, batch_size=min(batch_size, len(train_ds)),
        shuffle=True, generator=torch.Generator().manual_seed(seed + 1),
    )

    net.to(device)
    opt = Adam(net.parameters(), lr=lr)
    loss_fn = nn.MSELoss()

    train_losses, val_losses = [], []
    for _epoch in range(epochs):
        net.train()
        epoch_train_loss = 0.0
        n_seen = 0
        for batch_p, batch_b, batch_t in train_loader:
            batch_p = batch_p.to(device)
            batch_b = batch_b.to(device)
            batch_t = batch_t.to(device)
            preds = _batched_forward(net, batch_p, batch_b)
            loss = loss_fn(preds, batch_t)
            opt.zero_grad()
            loss.backward()
            opt.step()
            epoch_train_loss += loss.item() * batch_p.shape[0]
            n_seen += batch_p.shape[0]
        train_losses.append(epoch_train_loss / max(n_seen, 1))

        if val_ds is not None:
            net.eval()
            with torch.no_grad():
                vp = torch.stack([val_ds[i][0] for i in range(len(val_ds))]).to(device)
                vb = torch.stack([val_ds[i][1] for i in range(len(val_ds))]).to(device)
                vt = torch.stack([val_ds[i][2] for i in range(len(val_ds))]).to(device)
                vpreds = _batched_forward(net, vp, vb)
                val_losses.append(loss_fn(vpreds, vt).item())
        else:
            val_losses.append(float("nan"))
    return {"train_losses": train_losses, "val_losses": val_losses}


def _batched_forward(net, proposers: torch.Tensor, beliefs: torch.Tensor) -> torch.Tensor:
    """Run ValueNetwork.forward on a batch. The net is single-instance so we
    loop; for laptop scale this is fine."""
    outs = [net.forward(int(p.item()), b) for p, b in zip(proposers, beliefs)]
    return torch.stack(outs, dim=0)


# ---------------------------------------------------------------------------
# endtoend_train — Algorithm 3 ENDTOENDTRAIN over the 45-network bank
# ---------------------------------------------------------------------------

def _game_parts_in_dependency_order() -> List[Tuple[int, int]]:
    """The 9 (s, f) game-parts in dependency order: deepest (s+f largest) first.

    Each part (s, f) depends on (s+1, f) and (s, f+1). Sorting by descending
    (s+f) gives a valid order.
    """
    parts = [(s, f) for s in range(3) for f in range(3)]
    parts.sort(key=lambda sf: -(sf[0] + sf[1]))
    return parts


def endtoend_train(
    value_bank: ValueBank,
    *,
    n_samples_per_part: int = 200,
    n_cfr_iters: int = 100,
    averaging_delay: int = 0,
    epochs: int = 500,
    batch_size: int = 4096,
    lr: float = 1e-3,
    val_split: float = 0.1,
    device: str = "cpu",
    seed: int = 0,
    progress: bool = False,
) -> Dict[Tuple[int, int, int], Dict[str, list]]:
    """Train all 45 networks in dependency order. Returns per-key training history.

    Defaults are the laptop scale (Q4=a). For the user's hardware (Q4=b)
    bump n_samples_per_part to 2000+ and n_cfr_iters to 500+, and pass
    device='cuda' to train on GPU.
    """
    rng = np.random.default_rng(seed)
    history: Dict[Tuple[int, int, int], Dict[str, list]] = {}

    for s, f in _game_parts_in_dependency_order():
        for proposer in range(NUM_PLAYERS):
            if progress:
                print(f"[endtoend_train] training (proposer={proposer}, s={s}, f={f})")
            data = generate_datapoints(
                s=s, f=f, value_bank=value_bank,
                n_samples=n_samples_per_part,
                n_cfr_iters=n_cfr_iters,
                averaging_delay=averaging_delay,
                rng=rng,
            )
            net = value_bank.get(proposer, s, f)
            history[(proposer, s, f)] = train_value_network(
                net, data,
                epochs=epochs, batch_size=batch_size, lr=lr,
                val_split=val_split, device=device, seed=seed,
            )
    return history
